[build]
builder = "NIXPACKS"

[deploy]
preDeployCommand = "node scripts/ping-brrr.mjs"
startCommand = "npm start"
healthcheckPath = "/status"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
